/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CyberTwinXIntegrityInterface extends Interface {
    getFunction(nameOrSignature: "anchorMerkleRoot" | "getLatestRoot" | "getRootHistoryLength" | "getRootRecord" | "hasAnchoredRoot" | "verifyHistoricalRoot" | "verifyMerkleRoot"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MerkleRootAnchored"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorMerkleRoot', values: [string, BytesLike]): string;
encodeFunctionData(functionFragment: 'getLatestRoot', values: [string]): string;
encodeFunctionData(functionFragment: 'getRootHistoryLength', values: [string]): string;
encodeFunctionData(functionFragment: 'getRootRecord', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasAnchoredRoot', values: [string]): string;
encodeFunctionData(functionFragment: 'verifyHistoricalRoot', values: [string, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyMerkleRoot', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'anchorMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRootHistoryLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRootRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAnchoredRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyHistoricalRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyMerkleRoot', data: BytesLike): Result;
  }

  
    export namespace MerkleRootAnchoredEvent {
      export type InputTuple = [incidentId: string, merkleRoot: BytesLike, version: BigNumberish, timestamp: BigNumberish, registrar: AddressLike];
      export type OutputTuple = [incidentId: string, merkleRoot: string, version: bigint, timestamp: bigint, registrar: string];
      export interface OutputObject {incidentId: string, merkleRoot: string, version: bigint, timestamp: bigint, registrar: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CyberTwinXIntegrity extends BaseContract {
    
    connect(runner?: ContractRunner | null): CyberTwinXIntegrity;
    waitForDeployment(): Promise<this>;

    interface: CyberTwinXIntegrityInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorMerkleRoot: TypedContractMethod<
      [incidentId: string, merkleRoot: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getLatestRoot: TypedContractMethod<
      [incidentId: string, ],
      [[string, bigint, string, bigint] & {merkleRoot: string, timestamp: bigint, registrar: string, version: bigint }],
      'view'
    >
    

    
    getRootHistoryLength: TypedContractMethod<
      [incidentId: string, ],
      [bigint],
      'view'
    >
    

    
    getRootRecord: TypedContractMethod<
      [incidentId: string, index: BigNumberish, ],
      [[string, bigint, string, bigint] & {merkleRoot: string, timestamp: bigint, registrar: string, version: bigint }],
      'view'
    >
    

    
    hasAnchoredRoot: TypedContractMethod<
      [incidentId: string, ],
      [boolean],
      'view'
    >
    

    
    verifyHistoricalRoot: TypedContractMethod<
      [incidentId: string, version: BigNumberish, merkleRoot: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    verifyMerkleRoot: TypedContractMethod<
      [incidentId: string, merkleRoot: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorMerkleRoot'): TypedContractMethod<
      [incidentId: string, merkleRoot: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getLatestRoot'): TypedContractMethod<
      [incidentId: string, ],
      [[string, bigint, string, bigint] & {merkleRoot: string, timestamp: bigint, registrar: string, version: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getRootHistoryLength'): TypedContractMethod<
      [incidentId: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRootRecord'): TypedContractMethod<
      [incidentId: string, index: BigNumberish, ],
      [[string, bigint, string, bigint] & {merkleRoot: string, timestamp: bigint, registrar: string, version: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasAnchoredRoot'): TypedContractMethod<
      [incidentId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyHistoricalRoot'): TypedContractMethod<
      [incidentId: string, version: BigNumberish, merkleRoot: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyMerkleRoot'): TypedContractMethod<
      [incidentId: string, merkleRoot: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'MerkleRootAnchored'): TypedContractEvent<MerkleRootAnchoredEvent.InputTuple, MerkleRootAnchoredEvent.OutputTuple, MerkleRootAnchoredEvent.OutputObject>;

    filters: {
      
      'MerkleRootAnchored(string,bytes32,uint256,uint256,address)': TypedContractEvent<MerkleRootAnchoredEvent.InputTuple, MerkleRootAnchoredEvent.OutputTuple, MerkleRootAnchoredEvent.OutputObject>;
      MerkleRootAnchored: TypedContractEvent<MerkleRootAnchoredEvent.InputTuple, MerkleRootAnchoredEvent.OutputTuple, MerkleRootAnchoredEvent.OutputObject>;
    
    };
  }