const WHAT_IF_API = "http://localhost:5000/api/what-if";
const S={context:null,incidentId:null,stage:null,response:null,simulation:null,options:[],fallback:false};
const $=id=>document.getElementById(id);const E={stage:$('stageTimeline'),details:$('stageDetails'),bar:$('actionBarCard'),results:$('resultsCard'),eCount:$('evidenceEventCount'),confidence:$('evidenceConfidence'),evidence:$('evidenceList'),interpretation:$('modelInterpretation'),responses:$('responseOptions'),modeled:$('modeledDataBadge'),selection:$('actionSelectionText'),run:$('runSimulation'),reject:$('rejectResponse'),approve:$('approveResponse'),error:$('actionError'),confirm:$('decisionConfirmation'),risk:$('riskChangeMetric'),paths:$('attackPathsMetric'),state:$('securityStateMetric'),actual:$('actualPath'),whatif:$('whatIfPath'),changes:$('whatChanges'),remains:$('whatRemains'),message:$('stateMessage'),messageText:$('stateMessageText'),retry:$('retryWhatIf'),incidents:$('incidentSelector'),topEndpoint:$('topbarEndpoint'),topState:$('topbarState'),topRisk:$('topbarRisk'),topStatus:$('topbarSystemStatus'),sideStatus:$('sidebarSystemStatus')};
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const key=v=>String(v||'').trim().toUpperCase().replace(/[-\s]+/g,'_').replace(/[^A-Z0-9_]/g,'');
const canon=v=>({ACCOUNT_MODIFICATION:'USER_ACCOUNT_MODIFICATION',USER_ACCOUNT:'USER_ACCOUNT_MODIFICATION',PRIVILEGED:'PRIVILEGED_ACTIVITY',PRIVILEGE:'PRIVILEGE_ESCALATION'}[key(v)]||key(v));
const pretty=v=>String(v||'').replace(/^Endpoint:\s*/i,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim().replace(/\b\w/g,c=>c.toUpperCase());
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const show=x=>x?.classList.remove('hidden'),hide=x=>x?.classList.add('hidden');
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let p=null;try{p=await r.json()}catch{}if(!r.ok||p?.success===false)throw Error(p?.message||`Request failed with status ${r.status}`);return p}
async function loadIncidents(){if(!E.incidents)return[];const p=await api(`${WHAT_IF_API}/incidents`),a=Array.isArray(p.data)?p.data:[];E.incidents.innerHTML=a.length?a.map(i=>`<option value="${esc(i.incidentId)}">${esc(i.incidentId)} — ${esc(pretty(i.incidentType))}</option>`).join(''):'<option value="">No incidents available</option>';const id=new URLSearchParams(location.search).get('incidentId')||a[0]?.incidentId||null;S.incidentId=id;if(id)E.incidents.value=id;return a}
async function loadContext(id=S.incidentId){hide(E.message);const q=new URLSearchParams();if(id)q.set('incidentId',id);const p=await api(`${WHAT_IF_API}?${q}`);if(!p.data)throw Error('What-If context is empty.');S.context=p.data;S.incidentId=p.data.incident?.incidentId||id;S.stage=S.response=S.simulation=null;renderTop();renderStages();resetBelow()}
function renderTop(){const c=S.context||{},e=c.endpoint||{},a=c.actual||{};if(E.topEndpoint)E.topEndpoint.textContent=e.hostname||e.endpointId||'Unknown';if(E.topState)E.topState.textContent=a.securityState||e.securityState||'UNKNOWN';if(E.topRisk)E.topRisk.textContent=n(a.riskScore??e.riskScore);if(E.topStatus)E.topStatus.textContent=e.status||'UNKNOWN';if(E.sideStatus)E.sideStatus.textContent=`SYSTEM ${e.status||'UNKNOWN'}`}
function stages(){return[...new Set((S.context?.incident?.attackProgression||S.context?.actual?.attackProgression||[]).filter(Boolean))]}
function finding(stage){return(S.context?.actual?.findings||[]).find(f=>canon(f.type)===canon(stage))}
function evidence(stage){const a=Array.isArray(S.context?.evidence)?S.context.evidence:[],m=a.filter(x=>[x.type,x.category,x.description].some(v=>canon(v)===canon(stage)));if(m.length)return m;const f=finding(stage);return f?[{source:'Endpoint Twin',type:f.type,severity:f.severity,description:f.description,count:f.count}]:[]}
function renderStages(){const a=stages();E.stage.innerHTML=a.length?a.map((s,i)=>`<button type="button" class="stage-item" data-i="${i}"><span class="stage-number">${i+1}</span><span class="stage-name">${esc(pretty(s))}</span></button>`).join(''):'<div class="whatif-empty">No observed stages recorded for this incident.</div>';E.stage.querySelectorAll('.stage-item').forEach(b=>b.onclick=()=>selectStage(+b.dataset.i))}
function selectStage(i){const a=stages();if(!a[i])return;S.stage={index:i,value:a[i]};S.response=S.simulation=null;E.stage.querySelectorAll('.stage-item').forEach((b,j)=>b.classList.toggle('selected',i===j));renderEvidence(a[i]);renderResponses(a[i]);show(E.details);show(E.bar);resetSimulation()}
function renderEvidence(stage){const a=evidence(stage),f=finding(stage),count=a.reduce((s,x)=>s+Math.max(1,n(x.count,1)),0),conf=n(S.context?.endpoint?.evidenceConfidence??S.context?.incident?.confidence);E.eCount.textContent=count;E.confidence.textContent=`${conf}%`;E.evidence.innerHTML=a.slice(0,3).map(x=>`<li class="evidence-item"><strong>${esc(pretty(x.type||x.category||'Evidence'))}</strong><span>${esc(x.description||`${pretty(x.source||'Recorded evidence')} · ${pretty(x.severity||'Supporting')}`)}</span></li>`).join('')||'<li class="whatif-empty">No evidence recorded for this stage</li>';E.interpretation.textContent=f?.description||`The Incident Twin recorded ${pretty(stage)} as an observed stage with ${count} supporting event${count===1?'':'s'}.`}
function normalize(x,fallback=false){let impact=String(x.impact||x.disruption||'Medium').toLowerCase();return{action:x.action,name:x.name||x.action,effect:x.expectedEffect||x.description||'Models the effect of this response at the selected stage.',impact:impact[0].toUpperCase()+impact.slice(1),risk:x.simulatedRisk??null,paths:x.simulatedAttackPaths??null,state:x.simulatedSecurityState||x.state||null,remains:x.whatRemains||'Activity outside the response scope can still remain.',riskDelta:x.riskDelta,pathDelta:x.pathDelta,fallback}}
function renderResponses(stage){const backend=(S.context?.responseScenarios||[]).filter(x=>x?.status!=='NOT_APPLICABLE').map(x=>normalize(x));const fb=(window.CYBERTWIN_WHAT_IF_FALLBACKS?.[canon(stage)]||window.CYBERTWIN_WHAT_IF_FALLBACK_DEFAULT||[]).map(x=>normalize(x,true));const map=new Map(backend.map(x=>[x.action,x]));fb.forEach(x=>{if(!map.has(x.action))map.set(x.action,x)});S.options=[...map.values()].slice(0,3);S.fallback=backend.length<2||S.options.some(x=>x.fallback);if(S.options.length<2)S.fallback=true;E.modeled.classList.toggle('hidden',!S.fallback);E.responses.innerHTML=S.options.map((x,i)=>`<button type="button" class="response-option" data-i="${i}"><span class="response-option-head"><span class="response-option-name">${esc(x.name)}</span><span class="impact-tag impact-${x.impact.toLowerCase()}">${esc(x.impact)}</span></span><span class="response-effect">${esc(x.effect)}</span><span class="response-outcome">Modeled outcome: <strong>${x.risk==null?'runs on simulation':`risk ${n(x.risk)}`}</strong>${x.paths==null?'':` · ${n(x.paths)} path${n(x.paths)===1?'':'s'}`}${x.state?` · ${esc(pretty(x.state))}`:''}</span></button>`).join('')||'<div class="whatif-empty">No response options are available for this stage.</div>';E.responses.querySelectorAll('.response-option').forEach(b=>b.onclick=()=>selectResponse(+b.dataset.i))}
function selectResponse(i){S.response=S.options[i];S.simulation=null;E.responses.querySelectorAll('.response-option').forEach((b,j)=>b.classList.toggle('selected',i===j));E.selection.textContent=`Selected: ${S.response.name}`;resetSimulation()}
function resetBelow(){hide(E.details);hide(E.bar);resetSimulation()}
function resetSimulation(){hide(E.results);hide(E.reject);hide(E.approve);show(E.run);E.selection.textContent=S.response?`Selected: ${S.response.name}`:'Choose a response';hide(E.error);hide(E.confirm)}
const currentRisk=()=>n(S.context?.actual?.riskScore??S.context?.endpoint?.riskScore??S.context?.incident?.riskScore),currentPaths=()=>n(S.context?.actual?.attackPaths),currentState=()=>S.context?.actual?.securityState||S.context?.endpoint?.securityState||S.context?.incident?.currentState||'Unknown';
function localSimulation(x){const r=currentRisk(),p=currentPaths(),sr=Math.max(0,r-n(x.riskDelta,15));return{actual:{riskScore:r,attackPaths:p,securityState:currentState()},simulation:{riskScore:sr,attackPaths:Math.max(0,p-n(x.pathDelta,1)),securityState:x.state||(sr>=60?'Compromised':sr>=25?'Suspicious':'Normal')},riskReduction:r-sr,impact:x.effect,responseScenario:{whatRemains:x.remains}}}
async function run(){if(!S.response){show(E.error);return}hide(E.error);try{const p=await api(`${WHAT_IF_API}/simulate`,{method:'POST',body:JSON.stringify({endpointId:S.context?.endpoint?.endpointId,incidentId:S.incidentId,attackType:S.stage.value,action:S.response.action})});S.simulation=p.data}catch(err){if(!S.response.fallback){E.error.textContent=err.message||'Couldn\'t run simulation.';show(E.error);return}S.simulation=localSimulation(S.response)}renderSimulation()}
function renderSimulation(){const r=S.simulation,a=r.actual||{},m=r.simulation||{},cr=n(a.riskScore,currentRisk()),sr=n(m.riskScore,cr),cp=n(a.attackPaths,currentPaths()),sp=n(m.attackPaths,cp),cs=a.securityState||currentState(),ss=m.securityState||'Unknown',drop=cr-sr;E.risk.textContent=`${cr} → ${sr}`;E.paths.textContent=`${cp} → ${sp}`;E.state.textContent=`${pretty(cs)} → ${pretty(ss)}`;const st=stages(),idx=S.stage.index;E.actual.innerHTML=st.map(x=>`<li>${esc(pretty(x))}</li>`).join('')||'<li class="path-note">No observed stages</li>';E.whatif.innerHTML=st.map((x,i)=>i<idx?`<li>${esc(pretty(x))}</li>`:i===idx?`<li class="applied">${esc(S.response.name)} applied</li>`:`<li class="disabled-stage">${esc(pretty(x))}</li>`).join('');E.changes.textContent=drop>0?`Stops the modeled attack here, risk drops by ${drop} point${drop===1?'':'s'}.`:(r.impact||'No modeled change was produced by this response.');E.remains.textContent=r.responseScenario?.whatRemains||S.response.remains;show(E.results);hide(E.run);show(E.reject);show(E.approve)}
async function decide(decision){if(!S.simulation)return;const record={incidentId:S.incidentId,endpointId:S.context?.endpoint?.endpointId,stage:S.stage.value,response:S.response.name,responseAction:S.response.action,simulatedResult:S.simulation,decision,timestamp:new Date().toISOString()};try{await api(`${WHAT_IF_API}/decisions`,{method:'POST',body:JSON.stringify(record)})}catch(e){console.warn('[CyberTwin] Decision persistence failed:',e)}hide(E.reject);hide(E.approve);E.confirm.textContent=decision==='APPROVED'?'Approved and recorded. No endpoint action was performed.':'Rejected and recorded. Pick another response to compare.';show(E.confirm)}
E.run?.addEventListener('click',run);E.approve?.addEventListener('click',()=>decide('APPROVED'));E.reject?.addEventListener('click',()=>decide('REJECTED'));E.retry?.addEventListener('click',boot);E.incidents?.addEventListener('change',async e=>{if(!e.target.value)return;const u=new URL(location.href);u.searchParams.set('incidentId',e.target.value);history.replaceState({},'',u);try{S.incidentId=e.target.value;await loadContext(S.incidentId)}catch(err){E.messageText.textContent=err.message;show(E.message)}});
async function boot(){try{await loadIncidents();await loadContext()}catch(e){console.error(e);E.stage.innerHTML='<div class="whatif-empty">Couldn\'t load incident data. Retry.</div>';E.messageText.textContent='Couldn\'t load incident data. Retry';show(E.message)}}
document.addEventListener('DOMContentLoaded',boot);
